# Generated by Django 6.0.7 on 2026-07-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], default='long', max_length=5)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('opened_on', models.DateField()),
                ('closed_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-opened_on', '-created_at'],
            },
        ),
    ]
