# Generated by Django 6.0.7 on 2026-07-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done')], default='open', max_length=10)),
                ('due_on', models.DateField(blank=True, null=True)),
                ('related_kind', models.CharField(blank=True, max_length=50)),
                ('related_id', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['status', 'due_on', '-created_at'],
            },
        ),
    ]
