- IT:
    - Hetzner:
        href: "https://console.hetzner.cloud"
        description: VPS
        icon: hetzner.png
    - Synology:
        href: "http://192.168.1.2:5000"
        description: NAS
        icon: synology.png
    - iDrive:
        href: "https://www.idrive.com"
        description: Backup
        icon: idrive.png

- Tasks:
    - Vikunja:
        href: "https://tasks.khale.net"
        description: Tasks
        icon: vikunja.png
    - Google Calendar:
        href: "https://calendar.google.com"
        description: Calendar
        icon: google-calendar.png
