---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: brave
    target: _blank

- calendar:
    firstDayInWeek: monday
    view: list
    maxEvents: 10
    showTime: true
    timezone: Europe/London
    integrations:
      - type: ical
        url: https://calendar.google.com/calendar/ical/85c4875836a8c5ceee917720bc271aa05dd3a2a64217adeb8adfa5b5e889c027%40group.calendar.google.com/private-ae64d96e779dc4188b925f1328fd201d/basic.ics
        name: Personal
        color: blue

- customapi:
    url: https://zenquotes.io/api/random
    refreshInterval: 86400
    mappings:
      - field:
          0: q
        label: Quote
      - field:
          0: a
        label: Author
